name: Docker Image CI

on:
  push:
    branches:
      - 'main'

env:
  DOCKER_IMAGE: 'stpn77/clock:latest'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: docker login -U ${{secrets.DOCKER_ USER}} -p ${{secrets.DOCKER_PASSHORD}}
      - name: Build Docker image
        run: docker build . -t $DOCKER_IMAGE
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE
